apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: acrnbuk8s.azurecr.io/nbu-blog-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_BACKEND_URL
          value: "https://api.kubernetes.devinsights.site/api"
        - name: REACT_APP_KEYCLOAK_URL
          value: "https://kubernetes.devinsights.site/auth"
        - name: REACT_APP_KEYCLOAK_REALM
          value: "it-blog-realm"
        - name: REACT_APP_KEYCLOAK_CLIENT_ID
          value: "it-blog-client"
        - name: REACT_APP_API_URL
          value: "https://api.kubernetes.devinsights.site"
        - name: PUBLIC_URL
          value: "https://kubernetes.devinsights.site"

        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-internal
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP