apiVersion: v1
kind: Service
metadata:
  name: it-blog-api-service
  labels:
    app: it-blog-api
spec:
  selector:
    app: it-blog-api
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer