version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itblog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: itblog
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: password
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  postgres_data: