apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
  labels:
    app: blog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      containers:
      - name: blog-api
        image: blogacrcw3c.azurecr.io/blog-api:latest  # Replace XXXX with your suffix
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: POSTGRES_HOST
          value: "blog-postgres-cw3c.postgres.database.azure.com"  # Replace XXXX
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "pgadmin"
        - name: POSTGRES_PASSWORD
          value: "blogpassword"
        - name: NODE_ENV
          value: "production"
        - name: KEYCLOAK_URL
          value: "https://devinsights.site/auth"
        - name: KEYCLOAK_REALM
          value: "it-blog-realm"
        - name: KEYCLOAK_CLIENT_ID
          value: "it-blog-client"
        - name: FRONTEND_URL
          value: "https://devinsights.site"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: blog-api-internal
  labels:
    app: blog-api
spec:
  selector:
    app: blog-api
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP
---
