apiVersion: batch/v1
kind: Job
metadata:
  name: blog-api-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: acrnbuk8s.azurecr.io/nbu-blog-api:latest
        command: ["npm", "run", "migrate"]
        env:
        - name: POSTGRES_HOST
          value: "psql-nbu-blog-k8s.postgres.database.azure.com"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "nbu_devinsights_blog"
        - name: POSTGRES_USER
          value: "nbuadmin"
        - name: POSTGRES_PASSWORD
          value: "NbuSecurePassword123!"
        - name: NODE_ENV
          value: "production"
      backoffLimit: 3