apiVersion: batch/v1
kind: Job
metadata:
  name: blog-api-migration
  labels:
    app: blog-api-migration
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: blog-api-migration
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: acrnbuk8s.azurecr.io/nbu-blog-api:latest
        command: ["npm", "run", "migrate"]
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "psql-nbu-blog-k8s.postgres.database.azure.com"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "nbu_devinsights_blog"
        - name: POSTGRES_USER
          value: "nbuadmin"
        - name: POSTGRES_PASSWORD
          value: "NbuSecurePassword123!"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      # REMOVED: backoffLimit: 3 (this doesn't belong here)