apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-blog-api
  labels:
    app: it-blog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-blog-api
  template:
    metadata:
      labels:
        app: it-blog-api
    spec:
      containers:
      - name: it-blog-api
        image: it-blog-api-ts:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: KEYCLOAK_URL
          value: "http://keycloak-service:80"
        - name: KEYCLOAK_REALM
          value: "it-blog-realm"
        - name: KEYCLOAK_CLIENT_ID
          value: "it-blog-client"
        - name: FRONTEND_URL
          value: "http://localhost:3000"
        - name: KEYCLOAK_CLIENT_SECRET
          value: ""
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "itblog"
        - name: POSTGRES_USER
          value: "bloguser"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 30
          periodSeconds: 10