name: Deploy to Azure Functions

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]
    paths:
      - 'functions/backend-functions-ts/**'
      - 'functions/frontend-functions-ts/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'func-nbu-blog-api'
  AZURE_WEBAPP_NAME: 'app-nbu-blog-fe'
  REGISTRY_NAME: 'acrnbufrontend'
  IMAGE_NAME: 'nbu-blog-frontend'
  NODE_VERSION: '20.x'
  REACT_APP_ENTRA_CLIENT_ID: '1d40f916-03d8-41a4-859b-9431cff65d99'
  REACT_APP_ENTRA_AUTHORITY: 'https://devinsightsblog.ciamlogin.com/d1125adb-c883-4751-83de-4946aa0825ff'
  REACT_APP_BACKEND_URL: 'https://api.functions.devinsights.site/api'


jobs:
  test-backend:
    name: Test Backend Functions
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd functions/backend-functions-ts
        npm install

    - name: Run linter
      run: |
        cd functions/backend-functions-ts
        npm run lint || true  # Continue even if linting has warnings

    - name: Run backend tests
      run: |
        cd functions/backend-functions-ts
        npm run test 
      env:
        NODE_ENV: test
        CI: true

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: test-backend  # Only deploy if tests pass
    environment: functions
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Backend Functions
      run: |
        cd functions/backend-functions-ts
        npm install
        npm run build
        npm prune --production

    - name: Deploy Backend to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: functions/backend-functions-ts
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Login to Azure Container Registry
      run: az acr login --name ${{ env.REGISTRY_NAME }}

    - name: Build and Push Frontend Docker Image
      run: |
        cd functions/frontend-functions-ts
        
        # Build the Docker image with commit SHA
        docker build \
          --build-arg REACT_APP_ENTRA_CLIENT_ID=${{ env.REACT_APP_ENTRA_CLIENT_ID }} \
          --build-arg REACT_APP_ENTRA_AUTHORITY=${{ env.REACT_APP_ENTRA_AUTHORITY }} \
          --build-arg REACT_APP_BACKEND_URL=${{ env.REACT_APP_BACKEND_URL }} \
          -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
          .
        
        # Push both tags
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    - name: Deploy Frontend to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deployment Summary
      run: |
        echo "=========================================="
        echo "🎉 NBU DevInsights Deployment Successful!"
        echo "=========================================="
        echo ""
        echo "📊 Test Results:"
        echo "   ✅ All backend tests passed"
        echo "   ✅ Type checking passed"
        echo ""
        echo "🚀 Deployed Components:"
        echo "   ✅ Backend Functions: ${{ env.AZURE_FUNCTIONAPP_NAME }}"
        echo "   ✅ Frontend App: ${{ env.AZURE_WEBAPP_NAME }}"
        echo ""
        echo "🔗 Application URLs:"
        echo "   🌐 Frontend: https://functions.devinsights.site"
        echo "   🔗 API: https://api.functions.devinsights.site/api"
        echo ""
        echo "🔗 Azure URLs:"
        echo "   🌐 Frontend: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "   🔗 API: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
        echo ""
        echo "📦 Container Image:"
        echo "   ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}"