# .github/workflows/deploy-functions.yml
name: Deploy Azure Functions

on:
  push:
    branches: [main]
    paths: 
      - 'functions/backend-functions-ts/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'func-devinsights'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions/backend-functions-ts'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: functions  # Add this line to use environment secrets
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/package-lock.json

    - name: 'Install and build'
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm ci
        npm run build
        npm prune --production

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Test deployment'
      run: |
        sleep 30
        curl -f "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/health" || exit 1
        echo "✅ Functions deployment successful"

---
# .github/workflows/deploy-frontend.yml
name: Deploy Frontend to App Service

on:
  push:
    branches: [main]
    paths: 
      - 'functions/frontend-functions-ts/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'app-devinsights-frontend'
  AZURE_WEBAPP_PACKAGE_PATH: 'functions/frontend-functions-ts'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: functions  # Add this line to use environment secrets
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package-lock.json

    - name: 'Install and build'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        npm ci
        npm run build
      env:
        # Use custom domain for production builds
        REACT_APP_BACKEND_URL: 'https://api.devinsights.site'

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Test deployment'
      run: |
        sleep 30
        curl -f "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" || exit 1
        echo "✅ Frontend deployment successful"